### PR TITLE
skipping some pages in back-button functionality

### PR DESCRIPTION
**Pull request by bsko**
https://github.com/goodfootclub/specs/issues/16

skipping 'Create game' route on back button

### CODE REVIEW

**Comment by Igonato** [comment]
Shouldn't it also skip team/add and team/edit?

**Comment by bsko** [comment]
Hmm.. probably not always.. it should work when you're returning from picking new player to your team. Will work on it more. Routing is pretty complicated in our app.

**Comment by mrlafranchi** [comment]
I'm open to suggestions for simplifying routing.

**Comment by bsko** [comment]
@mrlafranchi , probably not needed, i have an idea how to handle it :)

**Comment by bsko** [comment]
Well, i tested it everywhere, found 2 bugs, fixed them and also fixed mentioned issues:

team/add - handled
team/edit - no need. There is no button with redirect from there. The only way is to go back. This case is handled 'out of the box'.

Should work perfectly now.

**Pull request merged**
